version: '3.7'

networks:
  payzer-local:
    name: payzer-local
    external: true

services:
  service-discovery:
    networks:
      - payzer-local
    build:
      context: .
      dockerfile: ./EurekaServer/Dockerfile.local
    volumes:
      - ./:/app
    ports:
      - 8082:8761
  api-gateway:
    networks:
      - payzer-local
    build:
      context: .
      dockerfile: ./SpringApiGateway/Dockerfile.local
    volumes:
      - ./:/app
    ports:
      - 8081:8089
    depends_on:
      - service-discovery