server:
  port: 8761
  base-url: http://local.michaeljdufresne.com:8082/

spring:
  application:
    name: service-discovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false